### PR TITLE
Fix relative URLs in CSS

### LINKED ISSUE #26: Relative URLs in built CSS are not right
I don't know if this is me but I can't figure out my bug in that case.

I have a component that has CSS linking an image like: `background-image: url('./image.jpg');`
When I build my library the CSS gets transpiled to: `background-image: url('media/image.jpg');`
But the image is copied to a folder called media in the build folder so the is like this:

build/
  css/
    index.css
    ...
  media/
    image.jpg
    ...

So the correct URL should be '../media/image.jpg'.

It's probably a small fix but I'm no webpack guru so I cant make a PR for it.

### PR DESCRIPTION
**Pull request by Bagera**
Fixes #26

### CODE REVIEW

**Comment by DimiMikadze** [comment]
HI @Bagera 

Thanks for sending PR, can you confirm it's working in production environment? I mean after publishing to NPM and then installing in project

**Comment by Bagera** [comment]
No I can not. sorry. I have just used it with `file:`. That should be quite similar but I'm not 100% sure.

**Comment by Bagera** [comment]
I have a published lib on npm that you can try. kitty-lib with the component KittyCard.
I had to add the `build/css` and `build/media` folders to the package.json files field as the files where otherwise omitted when you publish.
I have tested kitty-lib in an app of mine and it works.

**Comment by DimiMikadze** [comment]
Hi @Bagera closing this PR, because of this PR: https://github.com/DimiMikadze/create-react-library/pull/33, would love your opinion on it

**Comment by Bagera** [comment]
@DimiMikadze That looks like a more complete as it also deals with the hash issue.

**Pull request closed without merging**
