### PR TITLE
Docs Update

### LINKED ISSUE #54: TypeScript support
As create-react-app supports TypeScript, do you have any plan to support it as well?

### PR DESCRIPTION
**Pull request by panz3r**
#### Description of what you did:

- Updated `README` files to include a `Typescript Support` section (Fix #54)
- Updated `CHANGELOG` (as before I forgot this one 😅 )

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature
- [x] 📚 Documentation

#### Main update on the:

- [ ] lib
- [x] template

### CODE REVIEW

**Comment by DimiMikadze** [comment]
Hi @panz3r I just followed your instructions and it didn't worked, because it lacks information regarding creating an `tsconfig.json` file and editing extensions in `config/paths.js`, see full answer in here https://github.com/udilia/create-react-library/issues/54#issuecomment-491168374

After adding all of those information in Readme it will become pretty long, therefore i think we can create separate gist file for it and link it in Readme.

**Comment by panz3r** [comment]
> Hi @panz3r I just followed your instructions and it didn't worked, because it lacks information regarding creating an `tsconfig.json` file and editing extensions in `config/paths.js`, see full answer in here [#54 (comment)](https://github.com/udilia/create-react-library/issues/54#issuecomment-491168374)


Hi @DimiMikadze ,

This sounds strange, I tried locally and it worked. 

I suppose `tsconfig.json` is required but regarding the file extensions inside `config/paths.js` it is no longer required since the update to `create-react-app` v3.1.2 (extensions are appended automatically by the script).

> After adding all of those information in Readme it will become pretty long, therefore i think we can create separate gist file for it and link it in Readme.

I think this is a good idea to avoid polluting the `README` 👍

**Comment by DimiMikadze** [comment]
@panz3r I've removed section regarding file extension changes: https://gist.github.com/DimiMikadze/f25e1c5c70fa003953afd40fa9042517

What you think if We'll ad this gist to Readme file?

**Comment by DimiMikadze** [comment]
https://github.com/udilia/create-react-library/commit/b7eda9b7dbcd306b031b1fdce57182741a41701d

**Comment by panz3r** [comment]
@DimiMikadze I think it's good 👍

**Pull request closed without merging**
